### ISSUE TITLE
ERROR  Cannot start nuxt:  Cannot find package 'vite-plugin-pwa'

### ISSUE THREAD

**Issue by devloperabhishek** [vite-pwa/nuxt#14]
Getting below error: 

ERROR  Cannot start nuxt:  Cannot find package 'vite-plugin-pwa' imported from /home/projects/nuxt-starter-zevnog/node_modules/@vite-pwa/nuxt/dist/module.mjs

  at InternalError.get (https://nuxtstarterzevnog-al3j.w-credentialless.staticblitz.com/blitz.2913a9f2fedb71678a44d5a6b5e0b08a6f00d17f.js:6:292489)
  at eval (file://node_modules/nuxi/dist/shared/nuxi.70a5067d.mjs:27:15129)
  at Array.map (<anonymous>)
  at Vu.formatArgs (file://node_modules/nuxi/dist/shared/nuxi.70a5067d.mjs:27:15100)
  at Vu.formatLogObj (file://node_modules/nuxi/dist/shared/nuxi.70a5067d.mjs:27:51806)
  at Vu.log (file://node_modules/nuxi/dist/shared/nuxi.70a5067d.mjs:27:15826)
  at Object.log (file://node_modules/nuxi/dist/cli.mjs:85:21)
  at _._log (file://node_modules/nuxi/dist/shared/nuxi.70a5067d.mjs:27:7823)
  at r (file://node_modules/nuxi/dist/shared/nuxi.70a5067d.mjs:27:7384)
  at _._logFn (file://node_modules/nuxi/dist/shared/nuxi.70a5067d.mjs:27:7775)
  at _.eval [as error] (file://node_modules/nuxi/dist/shared/nuxi.70a5067d.mjs:27:6561)
  at load (file://node_modules/nuxi/dist/chunks/dev.mjs:6829:37)
  at async Object.invoke (file://node_modules/nuxi/dist/chunks/dev.mjs:6873:5)
  at async _main (file://node_modules/nuxi/dist/cli.mjs:66:20)
![Capture](https://user-images.githubusercontent.com/54469874/217255192-73d4c636-8467-463e-a734-60bb2c456cb6.PNG)

after following steps:

npm i @vite-pwa/nuxt -D 

nuxt.config.ts : 

export default defineNuxtConfig({
  modules: ['@vite-pwa/nuxt'],
  pwa: {
    /* your pwa options */
  }
})

CODE : 
https://stackblitz.com/edit/nuxt-starter-zevnog?file=nuxt.config.ts

**Comment by userquin** [comment]
@devloperabhishek you should add the following packages (dev dependencies): 
- vite-plugin-pwa
- workbox-window
- workbox-build

**Comment by devloperabhishek** [comment]
Can't get solution (PWA icon / PWA install option)

after: 

"devDependencies": {
    "@vite-pwa/nuxt": "^0.0.4",
    "nuxt": "^3.1.2",
    "vite-plugin-pwa": "^0.14.2",
    "workbox-build": "^6.5.4",
    "workbox-window": "^6.5.4"
  }

You can check 
My code : https://stackblitz.com/edit/nuxt-starter-zevnog?file=nuxt.config.ts

**Comment by userquin** [comment]
@devloperabhishek pwa nuxt module doesn't provide any icon/manifest generation, you must provide the icons, if you want to generate the icons you have 2 options:
- use https://realfavicongenerator.net/, you only need an svg or a png
- use this another pwa module, will generate all icons for you: https://github.com/kevinmarrec/nuxt-pwa-module

We will progressively include improvements:
- web manifest variants: locales and theme color (WIP)
- icons and splash screen generation

About your repo on stackblizt, check this forked version https://stackblitz.com/edit/nuxt-starter-w4hbvn?file=nuxt.config.ts:
- you must add `<VitePwaManifest />` in `app.vue` or the `default.vue` layout: added in `app.vue`
- you must add the icons to manifest option in pwa module configuration entry, unfortunately you can't upload png images to stakblizt in the free version (that's my case), and so, only using an svg
- read the docs here: https://vite-pwa-org.netlify.app/frameworks/nuxt.html

You have an example here in playground, you can also check:
- [vitesse-nuxt3](https://github.com/antfu/vitesse-nuxt3/pull/75) (WIP)
- [Elk repo](https://github.com/elk-zone/elk): [Elk](https://elk.zone)

**Comment by devloperabhishek** [comment]
Thanks It works for me
