### ISSUE TITLE
Failed to load resource: the server responded with a status of 404

### ISSUE THREAD

**Issue by DidoMarchet** [vite-pwa/nuxt#174]
If I return to the website a few days after the latest deployment, I get this error, and the app crashes.

```javascript
Failed to load resource: the server responded with a status of 404 ()Understand this errorAI
console.js:36 [nuxt] Error fetching app manifest. FetchError: [GET] “/_nuxt/builds/meta/0d7d8353-1eb2-475f-a7e1-8b14be13c893.json”: 404
    at async o (ofetch.37386b05.mjs:268:15)
(anonymous) @ console.js:36
Show 1 more frame
Show lessUnderstand this errorAI
console.js:36 [nuxt] error caught during app initialization Xy: [GET] “/_nuxt/builds/meta/0d7d8353-1eb2-475f-a7e1-8b14be13c893.json”: 404
    at async o (https://zavaluce.it/_nuxt/NeSLdRRW.js:19:19811)Caused by: FetchError: [GET] “/_nuxt/builds/meta/0d7d8353-1eb2-475f-a7e1-8b14be13c893.json”: 404
    at async o (ofetch.37386b05.mjs:268:15)
(anonymous) @ console.js:36
Show 1 more frame
Show lessUnderstand this errorAI
console.js:36 Xy: [GET] “/_nuxt/builds/meta/0d7d8353-1eb2-475f-a7e1-8b14be13c893.json”: 404
    at async o (https://zavaluce.it/_nuxt/NeSLdRRW.js:19:19811)Caused by: FetchError: [GET] “/_nuxt/builds/meta/0d7d8353-1eb2-475f-a7e1-8b14be13c893.json”: 404
    at async o (ofetch.37386b05.mjs:268:15)
(anonymous) @ console.js:36
Show 1 more frame
Show lessUnderstand this errorAI
console.js:36 Hydration completed but contains mismatches.
(anonymous) @ console.js:36
Show 1 more frame
Show lessUnderstand this errorAI
```

If I clear all site data, it starts working again.

My configuration:

```javascript
export default {
  pwa: {
    registerWebManifestInRouteRules: true,
    scope: '/',
    base: '/',
    manifest: {
      name: process.env.SITE_NAME_FRONTEND,
      useWebmanifestExtension: false,
    },
    injectRegister: 'auto',
    registerType: 'autoUpdate',
    workbox: {
      globPatterns: ['**/*.{js,css,html,png,svg,ico}'],
      runtimeCaching: [
        {
          urlPattern: '/',
          handler: 'NetworkFirst',
        },
      ],
      navigateFallback: undefined,
    },
  },
}
```

How can I fix this issue?
Any advice would be appreciated because it's a bit problematic.

Thanks and kind regards;

Davide

**Comment by userquin** [comment]
Check cache headers for all your pages

**Comment by DidoMarchet** [comment]
Hi @userquin , thanks! Sorry to ask, but I’m not very experienced with PWAs 😅. I didn’t set any cache time myself, I’m just using netlify-edge with their cache settings. 
Are there any parameters I can change in my PWA configuration or my settings are ok?
Thanks and kind regards,
Davide
