### ISSUE TITLE
PreCache Strategy error.

### ISSUE THREAD

**Issue by phantodev** [vite-pwa/nuxt#72]
Hi guys... i have this error in my NUXT 3 APP... Can you help me please?

workbox-5357ef54.js:2582 Uncaught (in promise) bad-precaching-response: The precaching request for 'http://localhost:3000/' failed with an HTTP status of 404.
    at PrecacheStrategy._handleInstall (http://localhost:3000/workbox-5357ef54.js:2582:17)
    at async PrecacheStrategy._handle (http://localhost:3000/workbox-5357ef54.js:2511:18)
    at async PrecacheStrategy._getResponse (http://localhost:3000/workbox-5357ef54.js:2360:22)

**Comment by RomanKollerSnoop** [comment]
Same issue here... If someone knows the fix, please let me know.

**Comment by userquin** [comment]
you need to prerender navigate fallback page, by default `/`

**Comment by AnthonyCVP** [comment]
@userquin huh?
